name: Lazy Commit

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  make-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

        
    - name: Configure Git
      run: |
        # MAKE SURE TO REPLACE THESE!!
        git config --local user.email "zaydsimjee@gmail.com"
        git config --local user.name "Zayd Simjee"
        
    - name: Make random commits
      run: |
        NUM_COMMITS=$((RANDOM % 5 + 1))
        echo "Making $NUM_COMMITS commits today"
        
        for i in $(seq 1 $NUM_COMMITS); do
          if [ -f README.md ]; then
            TRAILING_LINES=$(awk '/^$/{p++} /^./{p=0} END{print p+0}' README.md)
          else
            echo "# Repository" > README.md
            TRAILING_LINES=0
          fi
          
          echo "Current trailing whitespace lines: $TRAILING_LINES"
          ACTION=$((RANDOM % 2))
          
          if [ $ACTION -eq 0 ] && [ $TRAILING_LINES -lt 2 ]; then
            echo "" >> README.md
            git add README.md
            git commit -m "Add whitespace to README"
          elif [ $ACTION -eq 1 ] && [ $TRAILING_LINES -gt 0 ]; then
            if [ "$(tail -n 1 README.md)" = "" ]; then
              head -n -1 README.md > README.md.tmp && mv README.md.tmp README.md
              git add README.md
              git commit -m "Remove whitespace from README"
            else
              echo "" >> README.md
              git add README.md
              git commit -m "Add temporary whitespace to README"
            fi
          else
            echo "" >> README.md
            git add README.md
            git commit -m "Add temporary whitespace to README"
            
            sleep 2
            
            head -n -1 README.md > README.md.tmp && mv README.md.tmp README.md
            git add README.md
            git commit -m "Remove temporary whitespace from README"
          fi
          git push
          sleep 3
        done
